#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""黄金ETF+期货组合仓位管理方案 PDF报告生成"""

import os, sys, json
import numpy as np

# ━━ Color Palette (auto-generated by pdf.py palette.generate) ━━
ACCENT       = __import__('reportlab.lib.colors', fromlist=['HexColor']).HexColor('#288fb1')
TEXT_PRIMARY  = __import__('reportlab.lib.colors', fromlist=['HexColor']).HexColor('#1e1d1b')
TEXT_MUTED    = __import__('reportlab.lib.colors', fromlist=['HexColor']).HexColor('#7b776f')
BG_SURFACE    = __import__('reportlab.lib.colors', fromlist=['HexColor']).HexColor('#e5e3df')
BG_PAGE       = __import__('reportlab.lib.colors', fromlist=['HexColor']).HexColor('#f3f2f0')

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, mm
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, Image,
    Table, TableStyle, KeepTogether, CondPageBreak
)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ═══════════════════════════════════════════════════════════════════
# Font Registration
# ═══════════════════════════════════════════════════════════════════

def _register_font(name, candidates):
    """candidates: [(path, subfontIndex|None), ...]，第一个可用的生效（macOS/Linux 自适应）"""
    for path, idx in candidates:
        if os.path.exists(path):
            try:
                if idx is None:
                    pdfmetrics.registerFont(TTFont(name, path))
                else:
                    pdfmetrics.registerFont(TTFont(name, path, subfontIndex=idx))
                return True
            except Exception:
                continue
    print(f"Font warning: no usable font for {name}")
    return False

# macOS: Songti/STHeiti (.ttc 需 subfontIndex) | Linux: Noto/LXGW/DejaVu
_SERIF      = [('/System/Library/Fonts/Supplemental/Songti.ttc', 3),
               ('/usr/share/fonts/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf', None)]
_SERIF_BOLD = [('/System/Library/Fonts/Supplemental/Songti.ttc', 1),
               ('/usr/share/fonts/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf', None)]
_SANS       = [('/System/Library/Fonts/STHeiti Light.ttc', 1),
               ('/usr/share/fonts/truetype/lxgw-wenkai/LXGWWenKai-Regular.ttf', None)]
_SANS_BOLD  = [('/System/Library/Fonts/STHeiti Medium.ttc', 1),
               ('/usr/share/fonts/truetype/lxgw-wenkai/LXGWWenKai-Medium.ttf', None)]
_LATIN      = [('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf', None)] + _SANS
_LATIN_BOLD = [('/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf', None)] + _SANS_BOLD

_register_font('NotoSerifSC', _SERIF)
_register_font('NotoSerifSC-Bold', _SERIF_BOLD)
_register_font('NotoSansSC', _SANS)
_register_font('NotoSansSC-Bold', _SANS_BOLD)
_register_font('DejaVuSans', _LATIN)
_register_font('DejaVuSans-Bold', _LATIN_BOLD)

registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('NotoSansSC', normal='NotoSansSC', bold='NotoSansSC-Bold')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans-Bold')

# ═══════════════════════════════════════════════════════════════════
# Styles
# ═══════════════════════════════════════════════════════════════════

PAGE_W, PAGE_H = A4
MARGIN_L = MARGIN_R = 0.85 * inch
MARGIN_T = MARGIN_B = 0.85 * inch
AVAIL_W = PAGE_W - MARGIN_L - MARGIN_R

h1_style = ParagraphStyle(name='H1', fontName='NotoSerifSC-Bold', fontSize=18,
    textColor=ACCENT, alignment=TA_LEFT, spaceBefore=24, spaceAfter=12, leading=26, wordWrap='CJK')

h2_style = ParagraphStyle(name='H2', fontName='NotoSerifSC-Bold', fontSize=14,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT, spaceBefore=18, spaceAfter=8, leading=20, wordWrap='CJK')

h3_style = ParagraphStyle(name='H3', fontName='NotoSansSC-Bold', fontSize=12,
    textColor=ACCENT, alignment=TA_LEFT, spaceBefore=12, spaceAfter=6, leading=17, wordWrap='CJK')

body_style = ParagraphStyle(name='Body', fontName='NotoSansSC', fontSize=10.5,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT, spaceBefore=0, spaceAfter=8, leading=17, wordWrap='CJK', firstLineIndent=21)

body_ni = ParagraphStyle(name='BodyNI', fontName='NotoSansSC', fontSize=10.5,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT, spaceBefore=0, spaceAfter=8, leading=17, wordWrap='CJK')

muted_style = ParagraphStyle(name='Muted', fontName='NotoSansSC', fontSize=9,
    textColor=TEXT_MUTED, alignment=TA_LEFT, spaceBefore=0, spaceAfter=6, leading=14, wordWrap='CJK')

callout_style = ParagraphStyle(name='Callout', fontName='NotoSansSC-Bold', fontSize=11,
    textColor=ACCENT, alignment=TA_LEFT, spaceBefore=8, spaceAfter=8, leading=17, wordWrap='CJK')

th_style = ParagraphStyle(name='TH', fontName='NotoSansSC-Bold', fontSize=10,
    textColor=colors.white, alignment=TA_CENTER, leading=14, wordWrap='CJK')

td_style = ParagraphStyle(name='TD', fontName='NotoSansSC', fontSize=9.5,
    textColor=TEXT_PRIMARY, alignment=TA_CENTER, leading=14, wordWrap='CJK')

td_left = ParagraphStyle(name='TDL', fontName='NotoSansSC', fontSize=9.5,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT, leading=14, wordWrap='CJK')

td_bold = ParagraphStyle(name='TDB', fontName='NotoSansSC-Bold', fontSize=9.5,
    textColor=TEXT_PRIMARY, alignment=TA_CENTER, leading=14, wordWrap='CJK')

# ═══════════════════════════════════════════════════════════════════
# Helpers
# ═══════════════════════════════════════════════════════════════════

def callout_box(text, bg='#e8f4f8', border=ACCENT):
    """Create a callout box with accent left border."""
    p = Paragraph(text, ParagraphStyle(name='CB', fontName='NotoSansSC', fontSize=10.5,
        textColor=TEXT_PRIMARY, alignment=TA_LEFT, leading=17, wordWrap='CJK',
        leftIndent=12, rightIndent=8, spaceBefore=6, spaceAfter=6))
    t = Table([[p]], colWidths=[AVAIL_W])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor(bg)),
        ('LINEBEFORE', (0,0), (0,-1), 3, border),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING', (0,0), (-1,-1), 0),
        ('RIGHTPADDING', (0,0), (-1,-1), 8),
    ]))
    return t

def stat_card(num, label, sub=''):
    """Small stat card."""
    num_p = Paragraph(f'<font name="NotoSerifSC-Bold" size="22" color="#288fb1">{num}</font>',
        ParagraphStyle(name='SN', alignment=TA_CENTER, leading=26))
    label_p = Paragraph(f'<font name="NotoSansSC" size="9" color="#7b776f">{label}</font>',
        ParagraphStyle(name='SL', alignment=TA_CENTER, leading=12))
    elements = [num_p, label_p]
    if sub:
        sub_p = Paragraph(f'<font name="NotoSansSC" size="8" color="#7b776f">{sub}</font>',
            ParagraphStyle(name='SS', alignment=TA_CENTER, leading=10))
        elements.append(sub_p)
    t = Table([elements], colWidths=[AVAIL_W/4 - 6])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f0f7fa')),
        ('TOPPADDING', (0,0), (-1,-1), 10),
        ('BOTTOMPADDING', (0,0), (-1,-1), 10),
        ('LEFTPADDING', (0,0), (-1,-1), 4),
        ('RIGHTPADDING', (0,0), (-1,-1), 4),
        ('LINEABOVE', (0,0), (-1,0), 2, ACCENT),
    ]))
    return t

def escape_xml(text):
    """Escape XML special characters for ReportLab Paragraph."""
    s = str(text)
    s = s.replace('&', '&amp;')
    s = s.replace('<', '&lt;')
    s = s.replace('>', '&gt;')
    return s

def make_table(headers, rows, col_ratios=None, highlight_rows=None):
    """Create a styled table."""
    if col_ratios is None:
        col_ratios = [1/len(headers)] * len(headers)
    col_widths = [r * AVAIL_W for r in col_ratios]

    data = [[Paragraph(h, th_style) for h in headers]]
    for row in rows:
        data.append([Paragraph(escape_xml(c), td_style if i > 0 else td_left) for i, c in enumerate(row)])

    t = Table(data, colWidths=col_widths, hAlign='CENTER')
    style_cmds = [
        ('BACKGROUND', (0,0), (-1,0), ACCENT),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#c0bdb6')),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('LEFTPADDING', (0,0), (-1,-1), 8),
        ('RIGHTPADDING', (0,0), (-1,-1), 8),
    ]
    # Alternating row colors
    for i in range(1, len(data)):
        if i % 2 == 0:
            style_cmds.append(('BACKGROUND', (0,i), (-1,i), BG_SURFACE))
        else:
            style_cmds.append(('BACKGROUND', (0,i), (-1,i), colors.white))
    # Highlight specific rows
    if highlight_rows:
        for r in highlight_rows:
            style_cmds.append(('BACKGROUND', (0,r), (-1,r), colors.HexColor('#fff3cd')))
            style_cmds.append(('FONTNAME', (0,r), (-1,r), 'NotoSansSC-Bold'))

    t.setStyle(TableStyle(style_cmds))
    return t

# ═══════════════════════════════════════════════════════════════════
# Load analysis data
# ═══════════════════════════════════════════════════════════════════

from gold_model.paths import EXECUTION_PLAN_DIR, ANALYSIS_JSON

with open(str(ANALYSIS_JSON), 'r') as f:
    A = json.load(f)

stats = A['signal_stats']
costs = A['cost_comparison']
rules = A['execution_rules']
scenarios = A['scenarios']
current = A['current']

CHARTS = str(EXECUTION_PLAN_DIR / 'charts')

# ═══════════════════════════════════════════════════════════════════
# Build Story
# ═══════════════════════════════════════════════════════════════════

story = []

# ─── Section 1: 核心发现 ───
story.append(Paragraph('一、核心发现', h1_style))

story.append(Paragraph(
    '对 V4.0 黄金预测模型在 2022.12~2026.06 期间的 1289 个交易日信号进行深度分析，'
    '提取了 881 次调仓记录，得出以下关键发现：', body_style))

# Stats cards row
cards = [
    stat_card('881', '总调仓次数', f'{stats["总交易日"]}交易日'),
    stat_card('1.5', '平均持仓天数', f'中位数{int(stats["持仓天数_中位数"])}天'),
    stat_card('20.5', '月均调仓', f'最多{stats["调仓最多月"]}次/月'),
    stat_card('27.4%', '空仓占比', '震荡市为主'),
]
card_table = Table([cards], colWidths=[AVAIL_W/4]*4)
card_table.setStyle(TableStyle([('VALIGN', (0,0), (-1,-1), 'TOP')]))
story.append(Spacer(1, 6))
story.append(card_table)
story.append(Spacer(1, 12))

story.append(callout_box(
    '<b>关键洞察：</b>V4 模型信号频率极高（日均 0.68 次调仓），但大部分是小幅微调（777/881=88%）。'
    '如果全部通过 ETF 执行，佣金 + 管理费将侵蚀大量收益。'
    '分层执行策略可以将年化成本从 0.43% 降至 0.19%，节省 56%。'
))

story.append(Paragraph('二、信号频率分析', h1_style))

story.append(Paragraph('2.1 仓位分布', h2_style))
story.append(Paragraph(
    f'分析区间内模型主要处于<b>震荡市</b>状态（1308天/100%），平均仓位 {stats["Regime统计"]["震荡"]["平均仓位"]:.2f}，'
    f'仓位标准差 {stats["Regime统计"]["震荡"]["仓位标准差"]:.2f}。'
    f'空仓占比 27.4%，说明模型在震荡市中有约 1/4 的时间选择观望。', body_style))

story.append(Image(f'{CHARTS}/position_distribution.png', width=AVAIL_W*0.75, height=AVAIL_W*0.75*0.625))
story.append(Paragraph('图1：V4模型仓位分布（2022.12~2026.06）', ParagraphStyle(
    name='Caption', fontName='NotoSansSC', fontSize=9, textColor=TEXT_MUTED,
    alignment=TA_CENTER, spaceBefore=4, spaceAfter=12)))

story.append(Paragraph('2.2 仓位时间序列', h2_style))
story.append(Paragraph(
    '从时间序列看，模型在 2023 年下半年至 2024 年上半年维持较高仓位（牛市配置），'
    '2024 下半年至 2025 年初仓位波动加大（震荡切换），2025 年后仓位趋于保守。'
    '空头信号极少出现（仅 101 天，7.8%），符合"牛市不做空"的非对称仓位原则。', body_style))

story.append(Image(f'{CHARTS}/position_timeseries.png', width=AVAIL_W, height=AVAIL_W*0.33))
story.append(Paragraph('图2：V3.0-E仓位信号时间序列', ParagraphStyle(
    name='Caption', fontName='NotoSansSC', fontSize=9, textColor=TEXT_MUTED,
    alignment=TA_CENTER, spaceBefore=4, spaceAfter=12)))

story.append(Paragraph('2.3 调仓频率与持仓周期', h2_style))
story.append(Paragraph(
    f'月均调仓 {stats["月均调仓次数"]:.1f} 次，最多一个月调仓 {stats["调仓最多月"]} 次，最少 {stats["调仓最少月"]} 次。'
    f'平均持仓周期仅 {stats["平均持仓天数"]:.1f} 天，中位数 1 天，最长连续持仓 {stats["持仓天数_最长"]} 天。'
    '这表明模型信号以日频微调为主，不适合全部通过 ETF 执行（ETF 虽然免印花税，但频繁申赎仍有摩擦成本）。', body_style))

story.append(Image(f'{CHARTS}/monthly_rebalance.png', width=AVAIL_W, height=AVAIL_W*0.33))
story.append(Paragraph('图3：月度调仓次数分布', ParagraphStyle(
    name='Caption', fontName='NotoSansSC', fontSize=9, textColor=TEXT_MUTED,
    alignment=TA_CENTER, spaceBefore=4, spaceAfter=12)))

story.append(Image(f'{CHARTS}/holding_period.png', width=AVAIL_W*0.8, height=AVAIL_W*0.8*0.5))
story.append(Paragraph('图4：持仓时长分布', ParagraphStyle(
    name='Caption', fontName='NotoSansSC', fontSize=9, textColor=TEXT_MUTED,
    alignment=TA_CENTER, spaceBefore=4, spaceAfter=12)))

story.append(callout_box(
    '<b>分层依据：</b>881 次调仓中，大调仓（仓位变化≥50%）仅 104 次（12%），'
    '小调仓 777 次（88%）。ETF 层只需处理大调仓（月均 1.7 次），期货层处理全部小调仓（月均 14 次），'
    '可将 ETF 交易频率降低 87%。'
))

# ─── Section 3: 成本对比 ───
story.append(Paragraph('三、成本对比分析', h1_style))

story.append(Paragraph(
    '以 V4 信号在 2022.12~2026.06 的实际调仓路径为基础，模拟三种执行方案的全成本：'
    '纯 ETF（518880）、纯期货（GC=F）、ETF+期货分层。'
    '成本包括交易佣金、ETF 管理费（0.6%/年）和期货保证金机会成本。', body_style))

story.append(Image(f'{CHARTS}/cost_comparison.png', width=AVAIL_W, height=AVAIL_W*0.42))
story.append(Paragraph('图5：不同资金规模下的成本对比', ParagraphStyle(
    name='Caption', fontName='NotoSansSC', fontSize=9, textColor=TEXT_MUTED,
    alignment=TA_CENTER, spaceBefore=4, spaceAfter=12)))

# Cost table
cost_rows = []
for cap in ['100000', '500000', '1000000', '5000000']:
    cap_label = f'¥{int(cap):,}'
    etf = costs[cap]['纯ETF']
    fut = costs[cap]['纯期货']
    hyb = costs[cap]['ETF+期货分层']
    n_years = stats['总交易日'] / 250
    usd = int(cap) / 7.2
    cost_rows.append([
        cap_label,
        f'{etf["总成本"]/n_years/usd*100:.2f}%',
        f'{fut["总成本"]/n_years/usd*100:.3f}%',
        f'{hyb["总成本"]/n_years/usd*100:.2f}%',
        f'{(1 - hyb["总成本"]/etf["总成本"])*100:.0f}%',
    ])

story.append(make_table(
    ['资金规模', '纯ETF年化', '纯期货年化', 'ETF+期货分层', '成本节省'],
    cost_rows,
    col_ratios=[0.2, 0.2, 0.2, 0.2, 0.2]
))
story.append(Paragraph('表1：不同资金规模下的年化成本率对比（含佣金+管理费+保证金机会成本）', ParagraphStyle(
    name='Caption', fontName='NotoSansSC', fontSize=9, textColor=TEXT_MUTED,
    alignment=TA_CENTER, spaceBefore=4, spaceAfter=12)))

story.append(callout_box(
    '<b>成本结论：</b>纯期货成本最低（0.03%/年），但需要海外期货账户且杠杆风险高。'
    'ETF+期货分层方案在可控风险下实现 0.19%/年的综合成本，较纯 ETF（0.43%/年）节省 56%。'
    '资金规模越大，分层方案的成本优势越明显（500万可节省 $8,922/年）。'
))

# ─── Section 4: 三层执行架构 ───
story.append(Paragraph('四、三层执行架构', h1_style))

story.append(Paragraph(
    '基于信号频率分析，设计三层执行架构：ETF 底仓层承载核心仓位、期货战术层处理精细调仓、'
    '现金层提供流动性缓冲。', body_style))

story.append(Image(f'{CHARTS}/execution_architecture.png', width=AVAIL_W*0.9, height=AVAIL_W*0.9*0.6))
story.append(Paragraph('图6：ETF+期货三层执行架构', ParagraphStyle(
    name='Caption', fontName='NotoSansSC', fontSize=9, textColor=TEXT_MUTED,
    alignment=TA_CENTER, spaceBefore=4, spaceAfter=12)))

story.append(Paragraph('4.1 ETF底仓层（518880）', h2_style))
story.append(Paragraph(
    f'<b>资金占比：</b>{rules["底仓层(ETF 518880)"]["资金占比"]}<br/>'
    f'<b>调仓触发：</b>{rules["底仓层(ETF 518880)"]["调仓触发"]}<br/>'
    f'<b>调仓频率：</b>{rules["底仓层(ETF 518880)"]["调仓频率"]}<br/>'
    f'<b>目标：</b>{rules["底仓层(ETF 518880)"]["目标"]}<br/>'
    f'<b>操作：</b>{rules["底仓层(ETF 518880)"]["操作"]}<br/>'
    f'<b>佣金：</b>{rules["底仓层(ETF 518880)"]["佣金"]}<br/>'
    f'<b>持有成本：</b>{rules["底仓层(ETF 518880)"]["持有成本"]}',
    body_ni))

story.append(Paragraph('4.2 期货战术层（COMEX GC=F）', h2_style))
story.append(Paragraph(
    f'<b>资金占比：</b>{rules["战术层(COMEX GC=F)"]["资金占比"]}<br/>'
    f'<b>调仓触发：</b>{rules["战术层(COMEX GC=F)"]["调仓触发"]}<br/>'
    f'<b>调仓频率：</b>{rules["战术层(COMEX GC=F)"]["调仓频率"]}<br/>'
    f'<b>目标：</b>{rules["战术层(COMEX GC=F)"]["目标"]}<br/>'
    f'<b>操作：</b>{rules["战术层(COMEX GC=F)"]["操作"]}<br/>'
    f'<b>佣金：</b>{rules["战术层(COMEX GC=F)"]["佣金"]}<br/>'
    f'<b>杠杆：</b>{rules["战术层(COMEX GC=F)"]["杠杆"]}',
    body_ni))

story.append(Paragraph('4.3 现金层', h2_style))
story.append(Paragraph(
    f'<b>资金占比：</b>{rules["现金层"]["资金占比"]}<br/>'
    f'<b>用途：</b>{rules["现金层"]["用途"]}<br/>'
    f'<b>收益：</b>{rules["现金层"]["收益"]}',
    body_ni))

story.append(callout_box(
    '<b>分层逻辑：</b>ETF 层用 65% 的资金承载核心仓位，仅在仓位变化≥0.3 或 Regime 切换时调仓，'
    '月均仅 1.7 次交易。期货层用 35% 的资金做精细调仓，处理日常 14 次/月的微调信号。'
    '由于期货杠杆约 20 倍，35% 资金的名义敞口可达 700%，足以覆盖战术调仓需求。'
))

# ─── Section 5: 情景执行手册 ───
story.append(Paragraph('五、情景执行手册', h1_style))

story.append(Paragraph(
    '根据模型输出的 Regime 状态和概率信号，分 5 种核心情景定义具体操作流程。'
    '每种场景下明确 ETF 层和期货层的仓位分配、操作顺序和注意事项。', body_style))

scen_rows = []
for s in scenarios:
    scen_rows.append([
        s['场景'],
        s['模型仓位'],
        s['ETF执行'],
        s['期货执行'],
        s['操作'],
    ])

story.append(make_table(
    ['场景', '模型仓位', 'ETF层', '期货层', '操作流程'],
    scen_rows,
    col_ratios=[0.18, 0.12, 0.15, 0.15, 0.40]
))
story.append(Paragraph('表2：五情景执行手册', ParagraphStyle(
    name='Caption', fontName='NotoSansSC', fontSize=9, textColor=TEXT_MUTED,
    alignment=TA_CENTER, spaceBefore=4, spaceAfter=12)))

story.append(callout_box(
    '<b>关键规则：</b><br/>'
    '1. ETF 不能做空 -- 熊市做空信号全部由期货层执行<br/>'
    '2. ETF T+0 交易 -- 当天可买卖，灵活进出<br/>'
    '3. 期货滑点更小 -- 止损时优先平期货腿<br/>'
    '4. 保证金监控 -- 期货层仓位超过 50% 时需追加保证金预警<br/>'
    '5. Regime 切换 -- 两腿同步调整，先平旧仓再开新仓'
))

# ─── Section 6: 风险管理 ───
story.append(Paragraph('六、风险管理规则', h1_style))

story.append(Paragraph('6.1 止损体系', h2_style))

story.append(make_table(
    ['层级', '触发条件', '操作', '恢复条件'],
    [
        ['单日止损', '单日亏损 > 3%', '期货层减仓50%', '次日重新评估信号'],
        ['组合止损', '累计回撤 > 8%', '两腿全部平仓', '空仓3天后重新建仓'],
        ['极端止损', '累计回撤 > 15%', '清仓 + 降杠杆', 'Regime明确反转后才恢复'],
        ['保证金止损', '保证金占用 > 70%', '减仓至50%以下', '保证金回落至50%以下'],
    ],
    col_ratios=[0.15, 0.25, 0.30, 0.30]
))
story.append(Paragraph('表3：四级止损体系', ParagraphStyle(
    name='Caption', fontName='NotoSansSC', fontSize=9, textColor=TEXT_MUTED,
    alignment=TA_CENTER, spaceBefore=4, spaceAfter=12)))

story.append(Paragraph('6.2 仓位限制', h2_style))
story.append(Paragraph(
    '<b>单一标的限制：</b>ETF 单一标的不超过总资金 70%；期货单一合约不超过总资金 50%（名义敞口）。<br/>'
    '<b>方向限制：</b>牛市/震荡市不做空（非对称仓位原则）；熊市不做多。<br/>'
    '<b>杠杆限制：</b>期货层实际杠杆不超过 5 倍（即名义敞口/期货层资金 ≤ 5）。<br/>'
    '<b>相关性限制：</b>ETF 和期货方向必须一致（同为多头或同为空头），禁止对锁。',
    body_ni))

story.append(Paragraph('6.3 日常监控清单', h2_style))
story.append(make_table(
    ['时间', '检查项', '频率', '行动阈值'],
    [
        ['盘前', '模型信号更新', '每日', '仓位变化>0即记录'],
        ['盘前', '保证金余额', '每日', '低于50%追加'],
        ['盘中', 'ETF价格 vs NAV', '每小时', '折价>0.5%可申赎套利'],
        ['盘中', '期货持仓盈亏', '每小时', '单日亏损>3%触发减仓'],
        ['盘后', '组合回撤', '每日', '累计>8%触发止损'],
        ['周报', '调仓记录汇总', '每周', '月偏差>50%需复盘'],
    ],
    col_ratios=[0.12, 0.28, 0.15, 0.45]
))
story.append(Paragraph('表4：日常监控清单', ParagraphStyle(
    name='Caption', fontName='NotoSansSC', fontSize=9, textColor=TEXT_MUTED,
    alignment=TA_CENTER, spaceBefore=4, spaceAfter=12)))

# ─── Section 7: 当前信号状态 ───
story.append(Paragraph('七、当前信号状态与操作建议', h1_style))

story.append(Paragraph(
    f'<b>当前 Regime：</b>{current["regime"]}<br/>'
    f'<b>当前仓位信号：</b>{current["position"]:.2f}（轻仓多）<br/>'
    f'<b>当前概率：</b>{current["probability"]:.1%}<br/>'
    f'<b>60日波动率：</b>{current["vol_60d"]:.1%}',
    body_ni))

story.append(callout_box(
    f'<b>当前操作建议：</b><br/>'
    f'Regime = {current["regime"]}，模型仓位 = {current["position"]:.0%}，概率 = {current["probability"]:.1%}<br/>'
    f'→ ETF层：建仓 518880 至 {current["position"]*0.65:.0%}（总资金的 {current["position"]*0.65:.0%}）<br/>'
    f'→ 期货层：开多 GC=F 至 {current["position"]*0.35:.0%}（总资金的 {current["position"]*0.35:.0%}）<br/>'
    f'→ 现金层：保留 {1-current["position"]:.0%} 作为保证金和缓冲<br/>'
    f'<b>注意：</b>当前为震荡市，模型仓位较轻。若概率降至 0.5 以下，ETF 层全部清仓。'
))

# ─── Section 8: 实施路径 ───
story.append(Paragraph('八、实施路径', h1_style))

story.append(make_table(
    ['阶段', '时间', '内容', '目标'],
    [
        ['Phase 1', '第1周', '开立券商账户 + 期货账户', '确保518880交易+GC=F交易权限'],
        ['Phase 2', '第2周', '接入V4模型每日信号推送', '建立信号→仓位→执行的SOP'],
        ['Phase 3', '第3-4周', '小资金试运行（10万）', '验证分层执行流程+成本'],
        ['Phase 4', '第2月', '扩大至目标资金规模', '满负荷运行三层架构'],
        ['Phase 5', '每月', '月度复盘 + 参数微调', '持续优化执行效率'],
    ],
    col_ratios=[0.10, 0.15, 0.40, 0.35]
))
story.append(Paragraph('表5：五阶段实施路径', ParagraphStyle(
    name='Caption', fontName='NotoSansSC', fontSize=9, textColor=TEXT_MUTED,
    alignment=TA_CENTER, spaceBefore=4, spaceAfter=12)))

story.append(Paragraph('8.1 账户要求', h2_style))
story.append(Paragraph(
    '<b>A股券商账户：</b>支持 518880 场内交易，佣金可谈至万一。推荐华泰/中信/东方财富。<br/>'
    '<b>海外期货账户：</b>支持 COMEX 黄金期货（GC=F）交易。推荐盈透证券(IBKR)/老虎证券。<br/>'
    '<b>资金通道：</b>海外账户需购汇+跨境汇款，每人每年 5 万美元便利化额度。<br/>'
    '<b>替代方案：</b>若无海外账户，期货层可用上海金交所 AU(T+D) 替代，但杠杆较低（约10倍）且有递延费。',
    body_ni))

story.append(Paragraph('8.2 信号接入', h2_style))
story.append(Paragraph(
    'V4 模型已部署为 FastAPI 后端（13 端点），支持 SSE 流式信号推送。'
    '每日盘前调用 /api/signal/latest 获取最新仓位信号，按本方案的分层规则拆分为 ETF 仓位和期货仓位，'
    '手动或半自动执行。Dashboard 前端支持人工调整滑块，可在模型信号基础上叠加主观判断。', body_ni))

story.append(callout_box(
    '<b>核心原则：</b>模型给方向，分层管成本，止损保生存。<br/>'
    'V4 模型的价值不在于预测多准（58%准确率），而在于仓位管理的纪律性 -- '
    '同样 58% 准确率，V2 亏钱 V3 赚钱，差距全在非对称仓位和止损规则。'
    '本执行方案是对"仓位管理"层面的最后一公里优化：让每次调仓的成本最低、执行最快。'
))

# ═══════════════════════════════════════════════════════════════════
# Build PDF
# ═══════════════════════════════════════════════════════════════════

OUTPUT_DIR = str(EXECUTION_PLAN_DIR)
BODY_PDF = f'{OUTPUT_DIR}/body.pdf'

doc = SimpleDocTemplate(BODY_PDF, pagesize=A4,
    leftMargin=MARGIN_L, rightMargin=MARGIN_R,
    topMargin=MARGIN_T, bottomMargin=MARGIN_B,
    title='黄金ETF+期货组合仓位管理方案', author='gold_model')

doc.build(story)
print(f"Body PDF generated: {BODY_PDF}")
